# Generated by Django 4.1.1 on 2023-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['posted', 'text', 'email'],
            },
        ),
    ]
